### ISSUE TITLE
Repeated use of same numbers in different files

### ISSUE THREAD

**Issue by mattgillucl** [UCL/kaska#105]
There are a few Kaska Python files which set the `block_size` to a default value of 256.

It would be better to have this numerical value set in just one file, which the others could reference where required.

**Comment by mattgillucl** [comment]
There could be others too (or at least at single-file scope)?

Constant values could be specified in a config file perhaps. Or create a new, small Python file with constants in for global use.

**Comment by mattgillucl** [comment]
I've just created a new branch, `constants`.

**Comment by mattgillucl** [comment]
The new branch does NOT update `smoothn.py` or its test code. That will have to be done once @timspainUCL's changes are merged into master. So please don't close this issue until that has been done.

**Comment by mattgillucl** [comment]
@timspainUCL Please have a look at your `smoothn` code and make changes if any are required. Then we can close this issue. Thanks.

**Comment by timspainUCL** [comment]
In `smoothn.py`, there are some unnamed, uncommented numerical parameters, but none are repeated such that they need parameterizing.

**Comment by mattgillucl** [comment]
Thanks Tim. OK, I'm going to close this issue then.
