### ISSUE TITLE
Sentinel 1 inversion

### ISSUE THREAD

**Issue by jgomezdans** [UCL/kaska#23]
Kaska should be used for inverting Sentinel 1 observations. We have been working on this, and the results are in [the sar_wcm branch](/UCL/kaska/tree/sar_wcm).

Status so far:
1. Implemented observation operator (WCM)
2. Implemented cost function
3. Implemented some tests to kick things off

All of the above have calculations for the model and cost function, the Jacobian and the Hessian, so we hope to be able to solve many pixels at a time.

There's some extra effort needed to read in data (not too big a hassle) and to construct a many pixels optimisation. It is also worth nothing that all the code is quite simple and might benefit from numba inlining.

@timspainUCL adding you as a reviewer for this ;-)

**Comment by dpshelio** [comment]
Closed as this branch has been merged.
