### ISSUE TITLE
Run a linter over all the files

### ISSUE THREAD

**Issue by dpshelio** [UCL/kaska#35]
Many files without an ending line. 
Also add such rule on `.editorconfig` and make sure everyone in the team has them in place

Proper order and grouping of imports (as [suggested by the pep8](https://www.python.org/dev/peps/pep-0008/#imports))

Add a check on travis or include https://pep8speaks.com/ to the repository.

**Comment by dpshelio** [comment]
[pep8speaks documentation](https://github.com/OrkoHunter/pep8speaks?installation_id=2238936&setup_action=install#configuration)

**Comment by timspainUCL** [comment]
Closing, at least for now, after @mattgillucl's sterling work.
