### ISSUE TITLE
Simplify comparissons

### ISSUE THREAD

**Issue by dpshelio** [UCL/kaska#37]
For example as in `_match_to_mask` in `kaska/s1_observations.py`
```python
if ( (x >= self.time_grid[0]) and (x <= self.time_grid[-1]))}
```

to
```python
if (self.time_grid[0] <= x <= self.time_grid[-1])
```

**Comment by mattgillucl** [comment]
@ilectra One of the lifting tools. finds issues such as this. I's either `pep8`/`pycodestyle` or `pylint`, but I can't remember which off hand.

**Comment by mattgillucl** [comment]
It is `pylint` and the relevant error code is:
`R1716: Simplify chained comparison between the operands (chained-comparison)`

**Comment by ilectra** [comment]
Cool! Has it been taken care of then in #108 ?

**Comment by mattgillucl** [comment]
Yes! I've just re-run `pylint` on the code and didn't get any of the `R1716` warnings. So we can close this.
