### ISSUE TITLE
Change of Travis imported GDAL breaks CI tests

### ISSUE THREAD

**Issue by timspainUCL** [UCL/kaska#87]
Between 14th November 16:39 and 15th November 10:00, the version of GDAL that Travis imports changed from 2.3.3 to 3.0.2. This causes the `test_reproject` and `test_utils` tests to fail when trying to get a GDAL projection.

It seems that GDAL version 3 introduced a new projection database(see http://osgeo-org.1560.x6.nabble.com/gdal-dev-Discoverability-of-the-new-proj-db-and-GDAL-DATA-PROJ-LIB-td5390848.html), which Travis seems unable to find correctly.

**Comment by timspainUCL** [comment]
The version I have been using on the Geography computers is 2.4.1.

**Comment by jgomezdans** [comment]
Maybe force gdal to not go over version 2.5.2

**Comment by timspainUCL** [comment]
Setting this condition in the .travis.yml allowed the Travis CI to complete.
commit cc3a4a065b09e69bb55d1fc52a702f78a2518cab on s2s1combo
